### ISSUE TITLE
EPIC: CoCoWoW - MVP

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/uds-package-dubbd#140]
This issue is to capture the full process / steps needed for a day 1/2 ops team to deploy the CoCoWoW package with an example mission app (podinfo). 

Assumption: There may be a series of steps post package deployment that need to be accomplished. Recommend we start with what is needed today and update those procedures as we discover / implement ways to automate.

- [x] BB Core/Keycloak are fully integrated (SSO enabled for BB apps)
  - [x] kiali
  - [x] tempo
  - [x] neuvector
  - [x] monitoring 
- [x] Keycloak & authservice are configured such that: 
  - [x] only the cluster admin KC group can access the above BB Core apps
  - [x] only the podinfo KC group can access podinfo
- [x] podinfo is fully integrated into bigbang
  - [x] istio injection is enabled and mTLS is strict
  - [x] metrics are collected by monitoring
  - [ ] logs are collected by PLG
  - [ ] network policies have been implemented / tested
  - [ ] tracing is enabled with tempo
- [ ] how we did this is declarative and/or fully documented in a repeatable manner

- [x] day 2 strategy for adding new applications BB Core / Keycloak / authservice is documented / captured

**Comment by oates** [comment]
@ntwkninja can we close this issue? Should it belong somewhere else instead of DUBBD repo

**Comment by ntwkninja** [comment]
OBE
