### ISSUE TITLE
Create base DUBBD distribution for RKE2/on-prem

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-package-dubbd#432]
To support deployments on-prem, we should develop a distribution of DUBBD targeted for RKE2 (as our chosen k8s distro for on-prem).

Requirements:
- DUBBD "on-prem" deploys on a pre-existing cluster RKE2
- Uses in-cluster storage (for Loki, etc) for now
- All services running from DUBBD

Separate issues will tackle the IaC portions to make this production ready/deployed on-prem.
```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-package-dubbd/issues/412
- [x] Create base folder/zarf.yaml for on-prem
- [x] Add necessary config to get zarf package running on rke2
- [x] Add workflows to test on RKE2 (pending CI/dev resource discussion)
```

**Comment by mjnagel** [comment]
https://github.com/defenseunicorns/uds-package-dubbd/issues/412 is connected to this.

**Comment by mjnagel** [comment]
Going to target a basic RKE2 install in CI on AWS.

**Comment by mjnagel** [comment]
This should be complete with the addition of CI and releases for RKE2.
