### ISSUE TITLE
IaC module for object storage on vSphere

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-package-dubbd#433]
To support persistence for Loki and backup storage for Velero we should develop an "s3 compatible" object storage module for deployment on VMWare. [This](https://www.vmware.com/products/cloud-director/object-storage-extension.html) looks like what we should be leveraging?

Requirements:
- Automated with terraform
- "Plug and play" with loki/velero (should be s3 compatible)
- Reusable for loki/velero (flexible to support different permissions/names/etc)
- Option for automated auth between k8s service account/pod and object storage

```[tasklist]
### Tasks
- [ ] Build IaC for generic object storage on vSphere
- [ ] Build/expand IaC to create necessary auth for storage
- [ ] Pull modules into zarf package and automate config of loki/velero with auth output
```

**Comment by mjnagel** [comment]
Going to close this based on discussions at SWF meetings - this will instead be in cluster rook/ceph likely.
