### ISSUE TITLE
IaC to deploy Nutanix VMs

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-package-dubbd#482]
To allow DUBBD deployments on-prem in Nutanix environments we should create IaC module(s) to handle creation of VMs on Nutanix (with applicable storage, networking, etc). This ticket assumes bare metal machine(s) exist, pre-provisioned with the Nutanix hypervisor.

Requirements:
- VMs should use the image from https://github.com/defenseunicorns/uds-rke2-image-builder by default
- VMs should have an opinionated configuration by default
- All storage and networking requirements satisfied for the VMs to network together
- Terraform should be used

```[tasklist]
### Tasks
- [ ] Repo created for IaC
- [ ] Terraform module(s) created to provision VMs
- [ ] Terraform module(s) created to provision networking
- [ ] Documented usage of terraform to handle VM creation
```

**Comment by mjnagel** [comment]
Repo created with some initial IaC in https://github.com/defenseunicorns/delivery-nutanix-iac/pull/2/files to handle VM creation + RKE2 clustering.

**Comment by jacobbmay** [comment]
Repo using the rke2 module from the delivery-nutanix-iac repo: https://github.com/defenseunicorns/delivery-nutanix-cluster-deployment/pull/1

Decided to keep the deployment and modules separate.
